// Authorization messages for Insta360 BLE protocol.
// Reverse-engineered from libOne.so via Ghidra decompilation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/protocol/protobuf/authorization.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InitiatorType indicates who triggered the authorization check.
// Values from CheckAuthorization_InitiatorType_IsValid bitmask 0x10007000f.
type CheckAuthorization_InitiatorType int32

const (
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_DEFAULT        CheckAuthorization_InitiatorType = 0
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_USER           CheckAuthorization_InitiatorType = 1
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_APP            CheckAuthorization_InitiatorType = 2
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_SYSTEM         CheckAuthorization_InitiatorType = 3
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_BACKGROUND     CheckAuthorization_InitiatorType = 16
	CheckAuthorization_InitiatorType_INITIATOR_TYPE_AUTO_RECONNECT CheckAuthorization_InitiatorType = 32
)

// Enum value maps for CheckAuthorization_InitiatorType.
var (
	CheckAuthorization_InitiatorType_name = map[int32]string{
		0:  "INITIATOR_TYPE_DEFAULT",
		1:  "INITIATOR_TYPE_USER",
		2:  "INITIATOR_TYPE_APP",
		3:  "INITIATOR_TYPE_SYSTEM",
		16: "INITIATOR_TYPE_BACKGROUND",
		32: "INITIATOR_TYPE_AUTO_RECONNECT",
	}
	CheckAuthorization_InitiatorType_value = map[string]int32{
		"INITIATOR_TYPE_DEFAULT":        0,
		"INITIATOR_TYPE_USER":           1,
		"INITIATOR_TYPE_APP":            2,
		"INITIATOR_TYPE_SYSTEM":         3,
		"INITIATOR_TYPE_BACKGROUND":     16,
		"INITIATOR_TYPE_AUTO_RECONNECT": 32,
	}
)

func (x CheckAuthorization_InitiatorType) Enum() *CheckAuthorization_InitiatorType {
	p := new(CheckAuthorization_InitiatorType)
	*p = x
	return p
}

func (x CheckAuthorization_InitiatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAuthorization_InitiatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_authorization_proto_enumTypes[0].Descriptor()
}

func (CheckAuthorization_InitiatorType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_authorization_proto_enumTypes[0]
}

func (x CheckAuthorization_InitiatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAuthorization_InitiatorType.Descriptor instead.
func (CheckAuthorization_InitiatorType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{0}
}

// AuthorizationStatus indicates the camera's authorization state.
type CheckAuthorizationResp_AuthorizationStatus int32

const (
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_UNKNOWN        CheckAuthorizationResp_AuthorizationStatus = 0
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_AUTHORIZED     CheckAuthorizationResp_AuthorizationStatus = 1
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_NOT_AUTHORIZED CheckAuthorizationResp_AuthorizationStatus = 2
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_PENDING        CheckAuthorizationResp_AuthorizationStatus = 3
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_DENIED         CheckAuthorizationResp_AuthorizationStatus = 4
	CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_EXPIRED        CheckAuthorizationResp_AuthorizationStatus = 5
)

// Enum value maps for CheckAuthorizationResp_AuthorizationStatus.
var (
	CheckAuthorizationResp_AuthorizationStatus_name = map[int32]string{
		0: "AUTHORIZATION_STATUS_UNKNOWN",
		1: "AUTHORIZATION_STATUS_AUTHORIZED",
		2: "AUTHORIZATION_STATUS_NOT_AUTHORIZED",
		3: "AUTHORIZATION_STATUS_PENDING",
		4: "AUTHORIZATION_STATUS_DENIED",
		5: "AUTHORIZATION_STATUS_EXPIRED",
	}
	CheckAuthorizationResp_AuthorizationStatus_value = map[string]int32{
		"AUTHORIZATION_STATUS_UNKNOWN":        0,
		"AUTHORIZATION_STATUS_AUTHORIZED":     1,
		"AUTHORIZATION_STATUS_NOT_AUTHORIZED": 2,
		"AUTHORIZATION_STATUS_PENDING":        3,
		"AUTHORIZATION_STATUS_DENIED":         4,
		"AUTHORIZATION_STATUS_EXPIRED":        5,
	}
)

func (x CheckAuthorizationResp_AuthorizationStatus) Enum() *CheckAuthorizationResp_AuthorizationStatus {
	p := new(CheckAuthorizationResp_AuthorizationStatus)
	*p = x
	return p
}

func (x CheckAuthorizationResp_AuthorizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckAuthorizationResp_AuthorizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_authorization_proto_enumTypes[1].Descriptor()
}

func (CheckAuthorizationResp_AuthorizationStatus) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_authorization_proto_enumTypes[1]
}

func (x CheckAuthorizationResp_AuthorizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckAuthorizationResp_AuthorizationStatus.Descriptor instead.
func (CheckAuthorizationResp_AuthorizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{1}
}

// AuthorizationOperationType specifies the type of authorization request.
// Values from AuthorizationOperationType_IsValid: 0, 1, 2, 3.
type AuthorizationOperationType int32

const (
	AuthorizationOperationType_AUTHORIZATION_OPERATION_DEFAULT AuthorizationOperationType = 0
	AuthorizationOperationType_AUTHORIZATION_OPERATION_PAIR    AuthorizationOperationType = 1
	AuthorizationOperationType_AUTHORIZATION_OPERATION_REPAIR  AuthorizationOperationType = 2
	AuthorizationOperationType_AUTHORIZATION_OPERATION_UNPAIR  AuthorizationOperationType = 3
)

// Enum value maps for AuthorizationOperationType.
var (
	AuthorizationOperationType_name = map[int32]string{
		0: "AUTHORIZATION_OPERATION_DEFAULT",
		1: "AUTHORIZATION_OPERATION_PAIR",
		2: "AUTHORIZATION_OPERATION_REPAIR",
		3: "AUTHORIZATION_OPERATION_UNPAIR",
	}
	AuthorizationOperationType_value = map[string]int32{
		"AUTHORIZATION_OPERATION_DEFAULT": 0,
		"AUTHORIZATION_OPERATION_PAIR":    1,
		"AUTHORIZATION_OPERATION_REPAIR":  2,
		"AUTHORIZATION_OPERATION_UNPAIR":  3,
	}
)

func (x AuthorizationOperationType) Enum() *AuthorizationOperationType {
	p := new(AuthorizationOperationType)
	*p = x
	return p
}

func (x AuthorizationOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_authorization_proto_enumTypes[2].Descriptor()
}

func (AuthorizationOperationType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_authorization_proto_enumTypes[2]
}

func (x AuthorizationOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationOperationType.Descriptor instead.
func (AuthorizationOperationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{2}
}

// CheckAuthorization is sent by the phone/app to the camera (MessageCode 0x27).
type CheckAuthorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this app/device pairing (typically the BLE MAC address).
	AuthorizationId string `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	// Token for Find My device integration (optional).
	FindmyToken string `protobuf:"bytes,2,opt,name=findmy_token,json=findmyToken,proto3" json:"findmy_token,omitempty"`
	// Who initiated the authorization check.
	InitiatorType CheckAuthorization_InitiatorType `protobuf:"varint,3,opt,name=initiator_type,json=initiatorType,proto3,enum=insta360.messages.CheckAuthorization_InitiatorType" json:"initiator_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthorization) Reset() {
	*x = CheckAuthorization{}
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthorization) ProtoMessage() {}

func (x *CheckAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthorization.ProtoReflect.Descriptor instead.
func (*CheckAuthorization) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAuthorization) GetAuthorizationId() string {
	if x != nil {
		return x.AuthorizationId
	}
	return ""
}

func (x *CheckAuthorization) GetFindmyToken() string {
	if x != nil {
		return x.FindmyToken
	}
	return ""
}

func (x *CheckAuthorization) GetInitiatorType() CheckAuthorization_InitiatorType {
	if x != nil {
		return x.InitiatorType
	}
	return CheckAuthorization_InitiatorType_INITIATOR_TYPE_DEFAULT
}

// CheckAuthorizationResp is sent by the camera in response (MessageCode 0x8B).
type CheckAuthorizationResp struct {
	state               protoimpl.MessageState                     `protogen:"open.v1"`
	AuthorizationStatus CheckAuthorizationResp_AuthorizationStatus `protobuf:"varint,1,opt,name=authorization_status,json=authorizationStatus,proto3,enum=insta360.messages.CheckAuthorizationResp_AuthorizationStatus" json:"authorization_status,omitempty"`
	FindmyPairStatus    int32                                      `protobuf:"varint,2,opt,name=findmy_pair_status,json=findmyPairStatus,proto3" json:"findmy_pair_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckAuthorizationResp) Reset() {
	*x = CheckAuthorizationResp{}
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthorizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthorizationResp) ProtoMessage() {}

func (x *CheckAuthorizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthorizationResp.ProtoReflect.Descriptor instead.
func (*CheckAuthorizationResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAuthorizationResp) GetAuthorizationStatus() CheckAuthorizationResp_AuthorizationStatus {
	if x != nil {
		return x.AuthorizationStatus
	}
	return CheckAuthorizationResp_AuthorizationStatus_AUTHORIZATION_STATUS_UNKNOWN
}

func (x *CheckAuthorizationResp) GetFindmyPairStatus() int32 {
	if x != nil {
		return x.FindmyPairStatus
	}
	return 0
}

// RequestAuthorization is sent when camera reports not authorized (MessageCode 0x56).
type RequestAuthorization struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	OperationType AuthorizationOperationType `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=insta360.messages.AuthorizationOperationType" json:"operation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAuthorization) Reset() {
	*x = RequestAuthorization{}
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAuthorization) ProtoMessage() {}

func (x *RequestAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAuthorization.ProtoReflect.Descriptor instead.
func (*RequestAuthorization) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *RequestAuthorization) GetOperationType() AuthorizationOperationType {
	if x != nil {
		return x.OperationType
	}
	return AuthorizationOperationType_AUTHORIZATION_OPERATION_DEFAULT
}

// NotificationAuthorizationResult is sent by camera after user confirms (MessageCode 0x8A).
type NotificationAuthorizationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorized    bool                   `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAuthorizationResult) Reset() {
	*x = NotificationAuthorizationResult{}
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAuthorizationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAuthorizationResult) ProtoMessage() {}

func (x *NotificationAuthorizationResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAuthorizationResult.ProtoReflect.Descriptor instead.
func (*NotificationAuthorizationResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *NotificationAuthorizationResult) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

var File_pkg_protocol_protobuf_authorization_proto protoreflect.FileDescriptor

const file_pkg_protocol_protobuf_authorization_proto_rawDesc = "" +
	"\n" +
	")pkg/protocol/protobuf/authorization.proto\x12\x11insta360.messages\"\xbe\x01\n" +
	"\x12CheckAuthorization\x12)\n" +
	"\x10authorization_id\x18\x01 \x01(\tR\x0fauthorizationId\x12!\n" +
	"\ffindmy_token\x18\x02 \x01(\tR\vfindmyToken\x12Z\n" +
	"\x0einitiator_type\x18\x03 \x01(\x0e23.insta360.messages.CheckAuthorization_InitiatorTypeR\rinitiatorType\"\xb8\x01\n" +
	"\x16CheckAuthorizationResp\x12p\n" +
	"\x14authorization_status\x18\x01 \x01(\x0e2=.insta360.messages.CheckAuthorizationResp_AuthorizationStatusR\x13authorizationStatus\x12,\n" +
	"\x12findmy_pair_status\x18\x02 \x01(\x05R\x10findmyPairStatus\"l\n" +
	"\x14RequestAuthorization\x12T\n" +
	"\x0eoperation_type\x18\x01 \x01(\x0e2-.insta360.messages.AuthorizationOperationTypeR\roperationType\"A\n" +
	"\x1fNotificationAuthorizationResult\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized*\xcc\x01\n" +
	" CheckAuthorization_InitiatorType\x12\x1a\n" +
	"\x16INITIATOR_TYPE_DEFAULT\x10\x00\x12\x17\n" +
	"\x13INITIATOR_TYPE_USER\x10\x01\x12\x16\n" +
	"\x12INITIATOR_TYPE_APP\x10\x02\x12\x19\n" +
	"\x15INITIATOR_TYPE_SYSTEM\x10\x03\x12\x1d\n" +
	"\x19INITIATOR_TYPE_BACKGROUND\x10\x10\x12!\n" +
	"\x1dINITIATOR_TYPE_AUTO_RECONNECT\x10 *\x81\x02\n" +
	"*CheckAuthorizationResp_AuthorizationStatus\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_UNKNOWN\x10\x00\x12#\n" +
	"\x1fAUTHORIZATION_STATUS_AUTHORIZED\x10\x01\x12'\n" +
	"#AUTHORIZATION_STATUS_NOT_AUTHORIZED\x10\x02\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_PENDING\x10\x03\x12\x1f\n" +
	"\x1bAUTHORIZATION_STATUS_DENIED\x10\x04\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_EXPIRED\x10\x05*\xab\x01\n" +
	"\x1aAuthorizationOperationType\x12#\n" +
	"\x1fAUTHORIZATION_OPERATION_DEFAULT\x10\x00\x12 \n" +
	"\x1cAUTHORIZATION_OPERATION_PAIR\x10\x01\x12\"\n" +
	"\x1eAUTHORIZATION_OPERATION_REPAIR\x10\x02\x12\"\n" +
	"\x1eAUTHORIZATION_OPERATION_UNPAIR\x10\x03B:Z8github.com/xaionaro-go/insta360ctl/pkg/protocol/protobufb\x06proto3"

var (
	file_pkg_protocol_protobuf_authorization_proto_rawDescOnce sync.Once
	file_pkg_protocol_protobuf_authorization_proto_rawDescData []byte
)

func file_pkg_protocol_protobuf_authorization_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protobuf_authorization_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protobuf_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_authorization_proto_rawDesc), len(file_pkg_protocol_protobuf_authorization_proto_rawDesc)))
	})
	return file_pkg_protocol_protobuf_authorization_proto_rawDescData
}

var file_pkg_protocol_protobuf_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_protocol_protobuf_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_protobuf_authorization_proto_goTypes = []any{
	(CheckAuthorization_InitiatorType)(0),           // 0: insta360.messages.CheckAuthorization_InitiatorType
	(CheckAuthorizationResp_AuthorizationStatus)(0), // 1: insta360.messages.CheckAuthorizationResp_AuthorizationStatus
	(AuthorizationOperationType)(0),                 // 2: insta360.messages.AuthorizationOperationType
	(*CheckAuthorization)(nil),                      // 3: insta360.messages.CheckAuthorization
	(*CheckAuthorizationResp)(nil),                  // 4: insta360.messages.CheckAuthorizationResp
	(*RequestAuthorization)(nil),                    // 5: insta360.messages.RequestAuthorization
	(*NotificationAuthorizationResult)(nil),         // 6: insta360.messages.NotificationAuthorizationResult
}
var file_pkg_protocol_protobuf_authorization_proto_depIdxs = []int32{
	0, // 0: insta360.messages.CheckAuthorization.initiator_type:type_name -> insta360.messages.CheckAuthorization_InitiatorType
	1, // 1: insta360.messages.CheckAuthorizationResp.authorization_status:type_name -> insta360.messages.CheckAuthorizationResp_AuthorizationStatus
	2, // 2: insta360.messages.RequestAuthorization.operation_type:type_name -> insta360.messages.AuthorizationOperationType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protobuf_authorization_proto_init() }
func file_pkg_protocol_protobuf_authorization_proto_init() {
	if File_pkg_protocol_protobuf_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_authorization_proto_rawDesc), len(file_pkg_protocol_protobuf_authorization_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_protobuf_authorization_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protobuf_authorization_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_protobuf_authorization_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_protobuf_authorization_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protobuf_authorization_proto = out.File
	file_pkg_protocol_protobuf_authorization_proto_goTypes = nil
	file_pkg_protocol_protobuf_authorization_proto_depIdxs = nil
}
