// Live streaming messages for Insta360 WiFi protocol.
// Used over TCP port 6666 to control video preview streaming.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/protocol/protobuf/livestream.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VideoResolution identifies the stream resolution and frame rate.
// Values observed from reference implementations (RigacciOrg, WhiteBox).
type VideoResolution int32

const (
	VideoResolution_RES_UNKNOWN      VideoResolution = 0
	VideoResolution_RES_1440_720P30  VideoResolution = 9  // 1440x720 @ 30fps (dual fisheye)
	VideoResolution_RES_480_240P30   VideoResolution = 18 // 480x240 @ 30fps (low-res secondary)
	VideoResolution_RES_1920_1080P30 VideoResolution = 29 // 1920x1080 @ 30fps
	VideoResolution_RES_424_240P15   VideoResolution = 34 // 424x240 @ 15fps (thumbnail preview)
)

// Enum value maps for VideoResolution.
var (
	VideoResolution_name = map[int32]string{
		0:  "RES_UNKNOWN",
		9:  "RES_1440_720P30",
		18: "RES_480_240P30",
		29: "RES_1920_1080P30",
		34: "RES_424_240P15",
	}
	VideoResolution_value = map[string]int32{
		"RES_UNKNOWN":      0,
		"RES_1440_720P30":  9,
		"RES_480_240P30":   18,
		"RES_1920_1080P30": 29,
		"RES_424_240P15":   34,
	}
)

func (x VideoResolution) Enum() *VideoResolution {
	p := new(VideoResolution)
	*p = x
	return p
}

func (x VideoResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_livestream_proto_enumTypes[0].Descriptor()
}

func (VideoResolution) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_livestream_proto_enumTypes[0]
}

func (x VideoResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoResolution.Descriptor instead.
func (VideoResolution) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP(), []int{0}
}

// StartLiveStream is sent to begin video preview streaming (WiFi command code 1).
type StartLiveStream struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EnableAudio bool                   `protobuf:"varint,1,opt,name=enable_audio,json=enableAudio,proto3" json:"enable_audio,omitempty"`
	EnableVideo bool                   `protobuf:"varint,2,opt,name=enable_video,json=enableVideo,proto3" json:"enable_video,omitempty"`
	// field 3 = audioType enum (AACBSType), not commonly used
	AudioSampleRate  uint32          `protobuf:"varint,4,opt,name=audio_sample_rate,json=audioSampleRate,proto3" json:"audio_sample_rate,omitempty"`
	AudioBitrate     uint32          `protobuf:"varint,5,opt,name=audio_bitrate,json=audioBitrate,proto3" json:"audio_bitrate,omitempty"`
	VideoBitrate     uint32          `protobuf:"varint,6,opt,name=video_bitrate,json=videoBitrate,proto3" json:"video_bitrate,omitempty"`                // observed value: 40
	Resolution       VideoResolution `protobuf:"varint,7,opt,name=resolution,proto3,enum=insta360.messages.VideoResolution" json:"resolution,omitempty"` // primary stream resolution
	EnableGyro       bool            `protobuf:"varint,8,opt,name=enable_gyro,json=enableGyro,proto3" json:"enable_gyro,omitempty"`
	VideoBitrate1    uint32          `protobuf:"varint,9,opt,name=video_bitrate1,json=videoBitrate1,proto3" json:"video_bitrate1,omitempty"`                // secondary stream bitrate
	Resolution1      VideoResolution `protobuf:"varint,10,opt,name=resolution1,proto3,enum=insta360.messages.VideoResolution" json:"resolution1,omitempty"` // secondary stream resolution
	PreviewStreamNum uint32          `protobuf:"varint,11,opt,name=preview_stream_num,json=previewStreamNum,proto3" json:"preview_stream_num,omitempty"`    // number of preview streams (0 or 1)
	EnableRotate     bool            `protobuf:"varint,12,opt,name=enable_rotate,json=enableRotate,proto3" json:"enable_rotate,omitempty"`
	IsForLive        bool            `protobuf:"varint,13,opt,name=is_for_live,json=isForLive,proto3" json:"is_for_live,omitempty"` // true if streaming to external RTMP
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartLiveStream) Reset() {
	*x = StartLiveStream{}
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveStream) ProtoMessage() {}

func (x *StartLiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveStream.ProtoReflect.Descriptor instead.
func (*StartLiveStream) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP(), []int{0}
}

func (x *StartLiveStream) GetEnableAudio() bool {
	if x != nil {
		return x.EnableAudio
	}
	return false
}

func (x *StartLiveStream) GetEnableVideo() bool {
	if x != nil {
		return x.EnableVideo
	}
	return false
}

func (x *StartLiveStream) GetAudioSampleRate() uint32 {
	if x != nil {
		return x.AudioSampleRate
	}
	return 0
}

func (x *StartLiveStream) GetAudioBitrate() uint32 {
	if x != nil {
		return x.AudioBitrate
	}
	return 0
}

func (x *StartLiveStream) GetVideoBitrate() uint32 {
	if x != nil {
		return x.VideoBitrate
	}
	return 0
}

func (x *StartLiveStream) GetResolution() VideoResolution {
	if x != nil {
		return x.Resolution
	}
	return VideoResolution_RES_UNKNOWN
}

func (x *StartLiveStream) GetEnableGyro() bool {
	if x != nil {
		return x.EnableGyro
	}
	return false
}

func (x *StartLiveStream) GetVideoBitrate1() uint32 {
	if x != nil {
		return x.VideoBitrate1
	}
	return 0
}

func (x *StartLiveStream) GetResolution1() VideoResolution {
	if x != nil {
		return x.Resolution1
	}
	return VideoResolution_RES_UNKNOWN
}

func (x *StartLiveStream) GetPreviewStreamNum() uint32 {
	if x != nil {
		return x.PreviewStreamNum
	}
	return 0
}

func (x *StartLiveStream) GetEnableRotate() bool {
	if x != nil {
		return x.EnableRotate
	}
	return false
}

func (x *StartLiveStream) GetIsForLive() bool {
	if x != nil {
		return x.IsForLive
	}
	return false
}

// StartLiveStreamResp is an empty response confirming stream start (response code 200).
type StartLiveStreamResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLiveStreamResp) Reset() {
	*x = StartLiveStreamResp{}
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveStreamResp) ProtoMessage() {}

func (x *StartLiveStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveStreamResp.ProtoReflect.Descriptor instead.
func (*StartLiveStreamResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP(), []int{1}
}

// StopLiveStream is sent to stop the preview stream (WiFi command code 2).
type StopLiveStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLiveStream) Reset() {
	*x = StopLiveStream{}
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLiveStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLiveStream) ProtoMessage() {}

func (x *StopLiveStream) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLiveStream.ProtoReflect.Descriptor instead.
func (*StopLiveStream) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP(), []int{2}
}

// SyncLocalTimeToCamera is sent after sync handshake to synchronize time.
type SyncLocalTimeToCamera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   uint64                 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLocalTimeToCamera) Reset() {
	*x = SyncLocalTimeToCamera{}
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLocalTimeToCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLocalTimeToCamera) ProtoMessage() {}

func (x *SyncLocalTimeToCamera) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_livestream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLocalTimeToCamera.ProtoReflect.Descriptor instead.
func (*SyncLocalTimeToCamera) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP(), []int{3}
}

func (x *SyncLocalTimeToCamera) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_pkg_protocol_protobuf_livestream_proto protoreflect.FileDescriptor

const file_pkg_protocol_protobuf_livestream_proto_rawDesc = "" +
	"\n" +
	"&pkg/protocol/protobuf/livestream.proto\x12\x11insta360.messages\"\x92\x04\n" +
	"\x0fStartLiveStream\x12!\n" +
	"\fenable_audio\x18\x01 \x01(\bR\venableAudio\x12!\n" +
	"\fenable_video\x18\x02 \x01(\bR\venableVideo\x12*\n" +
	"\x11audio_sample_rate\x18\x04 \x01(\rR\x0faudioSampleRate\x12#\n" +
	"\raudio_bitrate\x18\x05 \x01(\rR\faudioBitrate\x12#\n" +
	"\rvideo_bitrate\x18\x06 \x01(\rR\fvideoBitrate\x12B\n" +
	"\n" +
	"resolution\x18\a \x01(\x0e2\".insta360.messages.VideoResolutionR\n" +
	"resolution\x12\x1f\n" +
	"\venable_gyro\x18\b \x01(\bR\n" +
	"enableGyro\x12%\n" +
	"\x0evideo_bitrate1\x18\t \x01(\rR\rvideoBitrate1\x12D\n" +
	"\vresolution1\x18\n" +
	" \x01(\x0e2\".insta360.messages.VideoResolutionR\vresolution1\x12,\n" +
	"\x12preview_stream_num\x18\v \x01(\rR\x10previewStreamNum\x12#\n" +
	"\renable_rotate\x18\f \x01(\bR\fenableRotate\x12\x1e\n" +
	"\vis_for_live\x18\r \x01(\bR\tisForLive\"\x15\n" +
	"\x13StartLiveStreamResp\"\x10\n" +
	"\x0eStopLiveStream\":\n" +
	"\x15SyncLocalTimeToCamera\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x04R\vtimestampMs*u\n" +
	"\x0fVideoResolution\x12\x0f\n" +
	"\vRES_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fRES_1440_720P30\x10\t\x12\x12\n" +
	"\x0eRES_480_240P30\x10\x12\x12\x14\n" +
	"\x10RES_1920_1080P30\x10\x1d\x12\x12\n" +
	"\x0eRES_424_240P15\x10\"B:Z8github.com/xaionaro-go/insta360ctl/pkg/protocol/protobufb\x06proto3"

var (
	file_pkg_protocol_protobuf_livestream_proto_rawDescOnce sync.Once
	file_pkg_protocol_protobuf_livestream_proto_rawDescData []byte
)

func file_pkg_protocol_protobuf_livestream_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protobuf_livestream_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protobuf_livestream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_livestream_proto_rawDesc), len(file_pkg_protocol_protobuf_livestream_proto_rawDesc)))
	})
	return file_pkg_protocol_protobuf_livestream_proto_rawDescData
}

var file_pkg_protocol_protobuf_livestream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_protobuf_livestream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_protocol_protobuf_livestream_proto_goTypes = []any{
	(VideoResolution)(0),          // 0: insta360.messages.VideoResolution
	(*StartLiveStream)(nil),       // 1: insta360.messages.StartLiveStream
	(*StartLiveStreamResp)(nil),   // 2: insta360.messages.StartLiveStreamResp
	(*StopLiveStream)(nil),        // 3: insta360.messages.StopLiveStream
	(*SyncLocalTimeToCamera)(nil), // 4: insta360.messages.SyncLocalTimeToCamera
}
var file_pkg_protocol_protobuf_livestream_proto_depIdxs = []int32{
	0, // 0: insta360.messages.StartLiveStream.resolution:type_name -> insta360.messages.VideoResolution
	0, // 1: insta360.messages.StartLiveStream.resolution1:type_name -> insta360.messages.VideoResolution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protobuf_livestream_proto_init() }
func file_pkg_protocol_protobuf_livestream_proto_init() {
	if File_pkg_protocol_protobuf_livestream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_livestream_proto_rawDesc), len(file_pkg_protocol_protobuf_livestream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_protobuf_livestream_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protobuf_livestream_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_protobuf_livestream_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_protobuf_livestream_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protobuf_livestream_proto = out.File
	file_pkg_protocol_protobuf_livestream_proto_goTypes = nil
	file_pkg_protocol_protobuf_livestream_proto_depIdxs = nil
}
