// WiFi configuration messages for Insta360 cameras.
// From official protobuf definitions in libOne.so (lib-one-proto package).
//
// Command codes:
//   SetWifiConnectionInfo = 112 (0x70)
//   GetWifiConnectionInfo = 113 (0x71)
//   SetWifiMode           = 147 (0x93)
//   GetWifiMode           = 150 (0x96)
//   GetWifiScanList       = 148 (0x94)
//   GetConnectedWifiList  = 149 (0x95)
//   ResetWifi             = 125 (0x7D)
//   DelWifiHistoryInfo    = 175 (0xAF)
//
// Notifications:
//   WifiStatus            = 8232 (0x2028)
//   WifiModeChange        = 8247 (0x2037)
//   WifiScanListChanged   = 8249 (0x2039)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/protocol/protobuf/wifi_config.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WifiMode identifies the camera's WiFi operating mode.
type WifiMode int32

const (
	WifiMode_WIFI_MODE_AP  WifiMode = 0 // Camera acts as access point (default)
	WifiMode_WIFI_MODE_STA WifiMode = 1 // Camera joins existing WiFi network (station mode)
	WifiMode_WIFI_MODE_P2P WifiMode = 2 // WiFi Direct / peer-to-peer
)

// Enum value maps for WifiMode.
var (
	WifiMode_name = map[int32]string{
		0: "WIFI_MODE_AP",
		1: "WIFI_MODE_STA",
		2: "WIFI_MODE_P2P",
	}
	WifiMode_value = map[string]int32{
		"WIFI_MODE_AP":  0,
		"WIFI_MODE_STA": 1,
		"WIFI_MODE_P2P": 2,
	}
)

func (x WifiMode) Enum() *WifiMode {
	p := new(WifiMode)
	*p = x
	return p
}

func (x WifiMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_wifi_config_proto_enumTypes[0].Descriptor()
}

func (WifiMode) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_wifi_config_proto_enumTypes[0]
}

func (x WifiMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiMode.Descriptor instead.
func (WifiMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{0}
}

// WifiConnectionResult indicates the outcome of a WiFi join attempt.
type WifiConnectionResult int32

const (
	WifiConnectionResult_WIFI_SUCCESS              WifiConnectionResult = 0
	WifiConnectionResult_WIFI_TIMEOUT              WifiConnectionResult = 1
	WifiConnectionResult_WIFI_ERROR_CONNECT_FAILED WifiConnectionResult = 2
)

// Enum value maps for WifiConnectionResult.
var (
	WifiConnectionResult_name = map[int32]string{
		0: "WIFI_SUCCESS",
		1: "WIFI_TIMEOUT",
		2: "WIFI_ERROR_CONNECT_FAILED",
	}
	WifiConnectionResult_value = map[string]int32{
		"WIFI_SUCCESS":              0,
		"WIFI_TIMEOUT":              1,
		"WIFI_ERROR_CONNECT_FAILED": 2,
	}
)

func (x WifiConnectionResult) Enum() *WifiConnectionResult {
	p := new(WifiConnectionResult)
	*p = x
	return p
}

func (x WifiConnectionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiConnectionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_protobuf_wifi_config_proto_enumTypes[1].Descriptor()
}

func (WifiConnectionResult) Type() protoreflect.EnumType {
	return &file_pkg_protocol_protobuf_wifi_config_proto_enumTypes[1]
}

func (x WifiConnectionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiConnectionResult.Descriptor instead.
func (WifiConnectionResult) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{1}
}

// WifiConnectionInfo describes a WiFi network and connection state.
type WifiConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          string                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`                   // Network name
	Bssid         string                 `protobuf:"bytes,2,opt,name=bssid,proto3" json:"bssid,omitempty"`                 // Access point MAC address (optional)
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`           // Network password
	IpAddr        string                 `protobuf:"bytes,4,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"` // IP address assigned after connection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiConnectionInfo) Reset() {
	*x = WifiConnectionInfo{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiConnectionInfo) ProtoMessage() {}

func (x *WifiConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiConnectionInfo.ProtoReflect.Descriptor instead.
func (*WifiConnectionInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{0}
}

func (x *WifiConnectionInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *WifiConnectionInfo) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WifiConnectionInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *WifiConnectionInfo) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

// SetWifiConnectionInfo tells the camera to join a WiFi network (command 0x70).
type SetWifiConnectionInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WifiConnectionInfo *WifiConnectionInfo    `protobuf:"bytes,1,opt,name=wifi_connection_info,json=wifiConnectionInfo,proto3" json:"wifi_connection_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetWifiConnectionInfo) Reset() {
	*x = SetWifiConnectionInfo{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWifiConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWifiConnectionInfo) ProtoMessage() {}

func (x *SetWifiConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWifiConnectionInfo.ProtoReflect.Descriptor instead.
func (*SetWifiConnectionInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{1}
}

func (x *SetWifiConnectionInfo) GetWifiConnectionInfo() *WifiConnectionInfo {
	if x != nil {
		return x.WifiConnectionInfo
	}
	return nil
}

// SetWifiConnectionInfoResp is the response to SetWifiConnectionInfo.
type SetWifiConnectionInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWifiConnectionInfoResp) Reset() {
	*x = SetWifiConnectionInfoResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWifiConnectionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWifiConnectionInfoResp) ProtoMessage() {}

func (x *SetWifiConnectionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWifiConnectionInfoResp.ProtoReflect.Descriptor instead.
func (*SetWifiConnectionInfoResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{2}
}

// GetWifiConnectionInfo queries the camera's current WiFi connection (command 0x71).
type GetWifiConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiConnectionInfo) Reset() {
	*x = GetWifiConnectionInfo{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiConnectionInfo) ProtoMessage() {}

func (x *GetWifiConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiConnectionInfo.ProtoReflect.Descriptor instead.
func (*GetWifiConnectionInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{3}
}

// GetWifiConnectionInfoResp returns the camera's current WiFi connection info.
type GetWifiConnectionInfoResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WifiConnectionInfo *WifiConnectionInfo    `protobuf:"bytes,1,opt,name=wifi_connection_info,json=wifiConnectionInfo,proto3" json:"wifi_connection_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWifiConnectionInfoResp) Reset() {
	*x = GetWifiConnectionInfoResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiConnectionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiConnectionInfoResp) ProtoMessage() {}

func (x *GetWifiConnectionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiConnectionInfoResp.ProtoReflect.Descriptor instead.
func (*GetWifiConnectionInfoResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{4}
}

func (x *GetWifiConnectionInfoResp) GetWifiConnectionInfo() *WifiConnectionInfo {
	if x != nil {
		return x.WifiConnectionInfo
	}
	return nil
}

// CameraWifiConnectionResult is a notification (code 8232) sent by the camera
// after attempting to join a WiFi network.
type CameraWifiConnectionResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WifiConnectionResult WifiConnectionResult   `protobuf:"varint,1,opt,name=wifi_connection_result,json=wifiConnectionResult,proto3,enum=insta360.messages.WifiConnectionResult" json:"wifi_connection_result,omitempty"`
	WifiConnectionInfo   *WifiConnectionInfo    `protobuf:"bytes,2,opt,name=wifi_connection_info,json=wifiConnectionInfo,proto3" json:"wifi_connection_info,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CameraWifiConnectionResult) Reset() {
	*x = CameraWifiConnectionResult{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraWifiConnectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraWifiConnectionResult) ProtoMessage() {}

func (x *CameraWifiConnectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraWifiConnectionResult.ProtoReflect.Descriptor instead.
func (*CameraWifiConnectionResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{5}
}

func (x *CameraWifiConnectionResult) GetWifiConnectionResult() WifiConnectionResult {
	if x != nil {
		return x.WifiConnectionResult
	}
	return WifiConnectionResult_WIFI_SUCCESS
}

func (x *CameraWifiConnectionResult) GetWifiConnectionInfo() *WifiConnectionInfo {
	if x != nil {
		return x.WifiConnectionInfo
	}
	return nil
}

// SetWifiMode sets the camera's WiFi operating mode (command 0x93).
type SetWifiMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceHolder   uint32                 `protobuf:"varint,1,opt,name=place_holder,json=placeHolder,proto3" json:"place_holder,omitempty"` // Reserved (send 0)
	WifiMode      WifiMode               `protobuf:"varint,2,opt,name=wifi_mode,json=wifiMode,proto3,enum=insta360.messages.WifiMode" json:"wifi_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWifiMode) Reset() {
	*x = SetWifiMode{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWifiMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWifiMode) ProtoMessage() {}

func (x *SetWifiMode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWifiMode.ProtoReflect.Descriptor instead.
func (*SetWifiMode) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{6}
}

func (x *SetWifiMode) GetPlaceHolder() uint32 {
	if x != nil {
		return x.PlaceHolder
	}
	return 0
}

func (x *SetWifiMode) GetWifiMode() WifiMode {
	if x != nil {
		return x.WifiMode
	}
	return WifiMode_WIFI_MODE_AP
}

// SetWifiModeResp is the response to SetWifiMode.
type SetWifiModeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWifiModeResp) Reset() {
	*x = SetWifiModeResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWifiModeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWifiModeResp) ProtoMessage() {}

func (x *SetWifiModeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWifiModeResp.ProtoReflect.Descriptor instead.
func (*SetWifiModeResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{7}
}

// GetWifiMode queries the camera's current WiFi mode (command 0x96).
type GetWifiMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiMode) Reset() {
	*x = GetWifiMode{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiMode) ProtoMessage() {}

func (x *GetWifiMode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiMode.ProtoReflect.Descriptor instead.
func (*GetWifiMode) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{8}
}

// GetWifiModeResp returns the camera's current WiFi mode.
type GetWifiModeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WifiMode      WifiMode               `protobuf:"varint,1,opt,name=wifi_mode,json=wifiMode,proto3,enum=insta360.messages.WifiMode" json:"wifi_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiModeResp) Reset() {
	*x = GetWifiModeResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiModeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiModeResp) ProtoMessage() {}

func (x *GetWifiModeResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiModeResp.ProtoReflect.Descriptor instead.
func (*GetWifiModeResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{9}
}

func (x *GetWifiModeResp) GetWifiMode() WifiMode {
	if x != nil {
		return x.WifiMode
	}
	return WifiMode_WIFI_MODE_AP
}

// WifiModeResult is returned in WifiModeChange notifications.
type WifiModeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WifiMode      WifiMode               `protobuf:"varint,1,opt,name=wifi_mode,json=wifiMode,proto3,enum=insta360.messages.WifiMode" json:"wifi_mode,omitempty"`
	ErrCode       int32                  `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiModeResult) Reset() {
	*x = WifiModeResult{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiModeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiModeResult) ProtoMessage() {}

func (x *WifiModeResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiModeResult.ProtoReflect.Descriptor instead.
func (*WifiModeResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{10}
}

func (x *WifiModeResult) GetWifiMode() WifiMode {
	if x != nil {
		return x.WifiMode
	}
	return WifiMode_WIFI_MODE_AP
}

func (x *WifiModeResult) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

// GetWifiScanInfo requests a WiFi scan (command 0x94).
type GetWifiScanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"` // Scan interval in seconds
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`       // Number of scans
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiScanInfo) Reset() {
	*x = GetWifiScanInfo{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiScanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiScanInfo) ProtoMessage() {}

func (x *GetWifiScanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiScanInfo.ProtoReflect.Descriptor instead.
func (*GetWifiScanInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{11}
}

func (x *GetWifiScanInfo) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *GetWifiScanInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetWifiScanInfoResp is the response to GetWifiScanInfo.
type GetWifiScanInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiScanInfoResp) Reset() {
	*x = GetWifiScanInfoResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiScanInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiScanInfoResp) ProtoMessage() {}

func (x *GetWifiScanInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiScanInfoResp.ProtoReflect.Descriptor instead.
func (*GetWifiScanInfoResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{12}
}

// WifiScanInfo describes a discovered WiFi network.
type WifiScanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bssid         string                 `protobuf:"bytes,1,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Frequency     uint32                 `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`                        // MHz
	SignalLevel   int32                  `protobuf:"varint,3,opt,name=signal_level,json=signalLevel,proto3" json:"signal_level,omitempty"` // dBm
	Flags         string                 `protobuf:"bytes,4,opt,name=flags,proto3" json:"flags,omitempty"`                                 // Security flags (e.g. "[WPA2-PSK-CCMP]")
	Ssid          string                 `protobuf:"bytes,5,opt,name=ssid,proto3" json:"ssid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiScanInfo) Reset() {
	*x = WifiScanInfo{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiScanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiScanInfo) ProtoMessage() {}

func (x *WifiScanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiScanInfo.ProtoReflect.Descriptor instead.
func (*WifiScanInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{13}
}

func (x *WifiScanInfo) GetBssid() string {
	if x != nil {
		return x.Bssid
	}
	return ""
}

func (x *WifiScanInfo) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *WifiScanInfo) GetSignalLevel() int32 {
	if x != nil {
		return x.SignalLevel
	}
	return 0
}

func (x *WifiScanInfo) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *WifiScanInfo) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

// WifiScanInfoList is sent in WifiScanListChanged notifications (code 8249).
type WifiScanInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WifiInfo      []*WifiScanInfo        `protobuf:"bytes,1,rep,name=wifi_info,json=wifiInfo,proto3" json:"wifi_info,omitempty"`
	ListCount     int32                  `protobuf:"varint,2,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiScanInfoList) Reset() {
	*x = WifiScanInfoList{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiScanInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiScanInfoList) ProtoMessage() {}

func (x *WifiScanInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiScanInfoList.ProtoReflect.Descriptor instead.
func (*WifiScanInfoList) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{14}
}

func (x *WifiScanInfoList) GetWifiInfo() []*WifiScanInfo {
	if x != nil {
		return x.WifiInfo
	}
	return nil
}

func (x *WifiScanInfoList) GetListCount() int32 {
	if x != nil {
		return x.ListCount
	}
	return 0
}

// GetWifiConnectList queries saved WiFi networks (command 0x95).
type GetWifiConnectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWifiConnectList) Reset() {
	*x = GetWifiConnectList{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiConnectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiConnectList) ProtoMessage() {}

func (x *GetWifiConnectList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiConnectList.ProtoReflect.Descriptor instead.
func (*GetWifiConnectList) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{15}
}

// GetWifiConnectListResp returns the list of saved WiFi networks.
type GetWifiConnectListResp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConnectList            []*WifiConnectionInfo  `protobuf:"bytes,1,rep,name=connect_list,json=connectList,proto3" json:"connect_list,omitempty"`
	ListCount              uint32                 `protobuf:"varint,2,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	CurrentWifiConnectInfo *WifiConnectionInfo    `protobuf:"bytes,3,opt,name=current_wifi_connect_info,json=currentWifiConnectInfo,proto3" json:"current_wifi_connect_info,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetWifiConnectListResp) Reset() {
	*x = GetWifiConnectListResp{}
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWifiConnectListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWifiConnectListResp) ProtoMessage() {}

func (x *GetWifiConnectListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_protobuf_wifi_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWifiConnectListResp.ProtoReflect.Descriptor instead.
func (*GetWifiConnectListResp) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP(), []int{16}
}

func (x *GetWifiConnectListResp) GetConnectList() []*WifiConnectionInfo {
	if x != nil {
		return x.ConnectList
	}
	return nil
}

func (x *GetWifiConnectListResp) GetListCount() uint32 {
	if x != nil {
		return x.ListCount
	}
	return 0
}

func (x *GetWifiConnectListResp) GetCurrentWifiConnectInfo() *WifiConnectionInfo {
	if x != nil {
		return x.CurrentWifiConnectInfo
	}
	return nil
}

var File_pkg_protocol_protobuf_wifi_config_proto protoreflect.FileDescriptor

const file_pkg_protocol_protobuf_wifi_config_proto_rawDesc = "" +
	"\n" +
	"'pkg/protocol/protobuf/wifi_config.proto\x12\x11insta360.messages\"s\n" +
	"\x12WifiConnectionInfo\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\tR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x02 \x01(\tR\x05bssid\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x17\n" +
	"\aip_addr\x18\x04 \x01(\tR\x06ipAddr\"p\n" +
	"\x15SetWifiConnectionInfo\x12W\n" +
	"\x14wifi_connection_info\x18\x01 \x01(\v2%.insta360.messages.WifiConnectionInfoR\x12wifiConnectionInfo\"\x1b\n" +
	"\x19SetWifiConnectionInfoResp\"\x17\n" +
	"\x15GetWifiConnectionInfo\"t\n" +
	"\x19GetWifiConnectionInfoResp\x12W\n" +
	"\x14wifi_connection_info\x18\x01 \x01(\v2%.insta360.messages.WifiConnectionInfoR\x12wifiConnectionInfo\"\xd4\x01\n" +
	"\x1aCameraWifiConnectionResult\x12]\n" +
	"\x16wifi_connection_result\x18\x01 \x01(\x0e2'.insta360.messages.WifiConnectionResultR\x14wifiConnectionResult\x12W\n" +
	"\x14wifi_connection_info\x18\x02 \x01(\v2%.insta360.messages.WifiConnectionInfoR\x12wifiConnectionInfo\"j\n" +
	"\vSetWifiMode\x12!\n" +
	"\fplace_holder\x18\x01 \x01(\rR\vplaceHolder\x128\n" +
	"\twifi_mode\x18\x02 \x01(\x0e2\x1b.insta360.messages.WifiModeR\bwifiMode\"\x11\n" +
	"\x0fSetWifiModeResp\"\r\n" +
	"\vGetWifiMode\"K\n" +
	"\x0fGetWifiModeResp\x128\n" +
	"\twifi_mode\x18\x01 \x01(\x0e2\x1b.insta360.messages.WifiModeR\bwifiMode\"e\n" +
	"\x0eWifiModeResult\x128\n" +
	"\twifi_mode\x18\x01 \x01(\x0e2\x1b.insta360.messages.WifiModeR\bwifiMode\x12\x19\n" +
	"\berr_code\x18\x02 \x01(\x05R\aerrCode\"C\n" +
	"\x0fGetWifiScanInfo\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x15\n" +
	"\x13GetWifiScanInfoResp\"\x8f\x01\n" +
	"\fWifiScanInfo\x12\x14\n" +
	"\x05bssid\x18\x01 \x01(\tR\x05bssid\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\rR\tfrequency\x12!\n" +
	"\fsignal_level\x18\x03 \x01(\x05R\vsignalLevel\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\tR\x05flags\x12\x12\n" +
	"\x04ssid\x18\x05 \x01(\tR\x04ssid\"o\n" +
	"\x10WifiScanInfoList\x12<\n" +
	"\twifi_info\x18\x01 \x03(\v2\x1f.insta360.messages.WifiScanInfoR\bwifiInfo\x12\x1d\n" +
	"\n" +
	"list_count\x18\x02 \x01(\x05R\tlistCount\"\x14\n" +
	"\x12GetWifiConnectList\"\xe3\x01\n" +
	"\x16GetWifiConnectListResp\x12H\n" +
	"\fconnect_list\x18\x01 \x03(\v2%.insta360.messages.WifiConnectionInfoR\vconnectList\x12\x1d\n" +
	"\n" +
	"list_count\x18\x02 \x01(\rR\tlistCount\x12`\n" +
	"\x19current_wifi_connect_info\x18\x03 \x01(\v2%.insta360.messages.WifiConnectionInfoR\x16currentWifiConnectInfo*B\n" +
	"\bWifiMode\x12\x10\n" +
	"\fWIFI_MODE_AP\x10\x00\x12\x11\n" +
	"\rWIFI_MODE_STA\x10\x01\x12\x11\n" +
	"\rWIFI_MODE_P2P\x10\x02*Y\n" +
	"\x14WifiConnectionResult\x12\x10\n" +
	"\fWIFI_SUCCESS\x10\x00\x12\x10\n" +
	"\fWIFI_TIMEOUT\x10\x01\x12\x1d\n" +
	"\x19WIFI_ERROR_CONNECT_FAILED\x10\x02B:Z8github.com/xaionaro-go/insta360ctl/pkg/protocol/protobufb\x06proto3"

var (
	file_pkg_protocol_protobuf_wifi_config_proto_rawDescOnce sync.Once
	file_pkg_protocol_protobuf_wifi_config_proto_rawDescData []byte
)

func file_pkg_protocol_protobuf_wifi_config_proto_rawDescGZIP() []byte {
	file_pkg_protocol_protobuf_wifi_config_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_protobuf_wifi_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_wifi_config_proto_rawDesc), len(file_pkg_protocol_protobuf_wifi_config_proto_rawDesc)))
	})
	return file_pkg_protocol_protobuf_wifi_config_proto_rawDescData
}

var file_pkg_protocol_protobuf_wifi_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_protocol_protobuf_wifi_config_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_protocol_protobuf_wifi_config_proto_goTypes = []any{
	(WifiMode)(0),                      // 0: insta360.messages.WifiMode
	(WifiConnectionResult)(0),          // 1: insta360.messages.WifiConnectionResult
	(*WifiConnectionInfo)(nil),         // 2: insta360.messages.WifiConnectionInfo
	(*SetWifiConnectionInfo)(nil),      // 3: insta360.messages.SetWifiConnectionInfo
	(*SetWifiConnectionInfoResp)(nil),  // 4: insta360.messages.SetWifiConnectionInfoResp
	(*GetWifiConnectionInfo)(nil),      // 5: insta360.messages.GetWifiConnectionInfo
	(*GetWifiConnectionInfoResp)(nil),  // 6: insta360.messages.GetWifiConnectionInfoResp
	(*CameraWifiConnectionResult)(nil), // 7: insta360.messages.CameraWifiConnectionResult
	(*SetWifiMode)(nil),                // 8: insta360.messages.SetWifiMode
	(*SetWifiModeResp)(nil),            // 9: insta360.messages.SetWifiModeResp
	(*GetWifiMode)(nil),                // 10: insta360.messages.GetWifiMode
	(*GetWifiModeResp)(nil),            // 11: insta360.messages.GetWifiModeResp
	(*WifiModeResult)(nil),             // 12: insta360.messages.WifiModeResult
	(*GetWifiScanInfo)(nil),            // 13: insta360.messages.GetWifiScanInfo
	(*GetWifiScanInfoResp)(nil),        // 14: insta360.messages.GetWifiScanInfoResp
	(*WifiScanInfo)(nil),               // 15: insta360.messages.WifiScanInfo
	(*WifiScanInfoList)(nil),           // 16: insta360.messages.WifiScanInfoList
	(*GetWifiConnectList)(nil),         // 17: insta360.messages.GetWifiConnectList
	(*GetWifiConnectListResp)(nil),     // 18: insta360.messages.GetWifiConnectListResp
}
var file_pkg_protocol_protobuf_wifi_config_proto_depIdxs = []int32{
	2,  // 0: insta360.messages.SetWifiConnectionInfo.wifi_connection_info:type_name -> insta360.messages.WifiConnectionInfo
	2,  // 1: insta360.messages.GetWifiConnectionInfoResp.wifi_connection_info:type_name -> insta360.messages.WifiConnectionInfo
	1,  // 2: insta360.messages.CameraWifiConnectionResult.wifi_connection_result:type_name -> insta360.messages.WifiConnectionResult
	2,  // 3: insta360.messages.CameraWifiConnectionResult.wifi_connection_info:type_name -> insta360.messages.WifiConnectionInfo
	0,  // 4: insta360.messages.SetWifiMode.wifi_mode:type_name -> insta360.messages.WifiMode
	0,  // 5: insta360.messages.GetWifiModeResp.wifi_mode:type_name -> insta360.messages.WifiMode
	0,  // 6: insta360.messages.WifiModeResult.wifi_mode:type_name -> insta360.messages.WifiMode
	15, // 7: insta360.messages.WifiScanInfoList.wifi_info:type_name -> insta360.messages.WifiScanInfo
	2,  // 8: insta360.messages.GetWifiConnectListResp.connect_list:type_name -> insta360.messages.WifiConnectionInfo
	2,  // 9: insta360.messages.GetWifiConnectListResp.current_wifi_connect_info:type_name -> insta360.messages.WifiConnectionInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_protocol_protobuf_wifi_config_proto_init() }
func file_pkg_protocol_protobuf_wifi_config_proto_init() {
	if File_pkg_protocol_protobuf_wifi_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_protobuf_wifi_config_proto_rawDesc), len(file_pkg_protocol_protobuf_wifi_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_protobuf_wifi_config_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_protobuf_wifi_config_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_protobuf_wifi_config_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_protobuf_wifi_config_proto_msgTypes,
	}.Build()
	File_pkg_protocol_protobuf_wifi_config_proto = out.File
	file_pkg_protocol_protobuf_wifi_config_proto_goTypes = nil
	file_pkg_protocol_protobuf_wifi_config_proto_depIdxs = nil
}
